var project_information = [{"title":"Recurrent Neural Rhythm",
                            "img_path":"project_images/null.jpg",
                            "description": "",
                            "type":"st",
                            "year":2018},
                            {"title":"Symbolic Oscillations",
                              "img_path":"project_images/null.jpg",
                              "description": "",
                              "type":"st",
                              "year":2018},
                            {"title":"Symbolic Oscillations",
                              "img_path":"project_images/null.jpg",
                              "description": "",
                              "type":"st",
                              "year":2018},
                            {"title":"Phases of Matter, in Space",
                              "img_path":"project_images/null.jpg",
                              "description": "",
                              "type":"st",
                              "year":2018},
                            {"title":"Plume/Ruse",
                              "img_path":"project_images/null.jpg",
                              "description": "",
                              "type":"st",
                              "year":2017},
                            {"title":"Microarchitecture Suite",
                              "img_path":"project_images/null.jpg",
                              "description": "",
                              "type":"st",
                              "year":2017},
                          {}];

{"title":"","img_path":"",":","","type":"","year":0}
